export const users = [
    {
        "id": "15677326",
        "id_ig": "jsh58035",
        "name": "Marti",
        "email": "marti_mar@gmail.com",
        "password": "123456",
        "avatar": "",
        "raffle_maked": [],
        "raffle_participate": [],
        "social_media": [],
    },
    {
        "id": "44677326",
        "id_ig": "pvx58035",
        "name": "",
        "email": "",
        "password": "",
        "avatar": "",
        "raffle_maked": [],
        "raffle_participate": [],
        "social_media": [],
    },
    {
        "id": "15677321",
        "id_ig": "xjf58035",
        "name": "",
        "email": "",
        "password": "",
        "avatar": "",
        "raffle_maked": [],
        "raffle_participate": [],
        "social_media": [],
    },
    {
        "id": "15677320",
        "id_ig": "ktb58035",
        "name": "",
        "email": "",
        "password": "",
        "avatar": "",
        "raffle_maked": [],
        "raffle_participate": [],
        "social_media": [],
    },

]